server:
  port: 8082

spring:
  application:
    name: farmer-service

  datasource:
    url: jdbc:mysql://localhost:3306/farmerdb?useSSL=false&serverTimezone=UTC
    username: root
    password: "sanjana@4113"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.cropdeal: DEBUG
  file:
    name: logs/admin-farmer-service.log